import { GoogleGenAI } from "@google/genai";
import type { VercelRequest, VercelResponse } from '@vercel/node';

const generateImage = async (ai: GoogleGenAI, prompt: string, config: object): Promise<string> => {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt,
        config,
    });
    
    const image = response.generatedImages?.[0]?.image?.imageBytes;
    if (!image) {
        throw new Error("API response missing image data.");
    }
    return image;
};

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { prompt, style } = req.body;

  if (!prompt || !style) {
    return res.status(400).json({ error: 'Missing required fields: prompt and style' });
  }

  // Get API key from environment variable (set in Vercel dashboard)
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    console.error('GEMINI_API_KEY environment variable is not set');
    return res.status(500).json({ error: 'Server configuration error: API key not set' });
  }

  try {
    const ai = new GoogleGenAI({ apiKey });

    const standardPrompt = `A modern, high-quality, professional app icon for a mobile app. The icon should be a simple, memorable, and visually striking vector graphic with a ${style} design style, suitable for display on a homescreen. Icon subject: "${prompt}"`;
    const faviconPrompt = `A simple, clean, and modern favicon for a website. The icon should be a very simple, memorable, and visually striking vector graphic with a ${style} design style, suitable for a browser tab. Icon subject: "${prompt}"`;
    const fgPrompt = `A modern, high-quality, professional app icon foreground for an Android adaptive icon. The icon should be a simple, memorable, and visually striking vector graphic with a ${style} design style. The main subject should be centered. The background MUST be transparent. Icon subject: "${prompt}"`;
    const bgPrompt = `A matching background for the app icon "${prompt}". It should be a simple color, gradient, or subtle pattern that complements the foreground icon with a ${style} design style. The background should fill the entire square. Do not include the icon subject in the background.`;
    const splashPrompt = `A modern, high-quality, professional splash screen for a mobile app, with a ${style} design style. The image should be simple and visually striking, suitable for a loading screen. The main subject, "${prompt}", should be centered, leaving ample empty space around the edges to avoid being cropped on different phone sizes.`;

    const [
        standardResponse,
        faviconImage,
        fgImage,
        bgImage,
        splashImage
    ] = await Promise.all([
        ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: standardPrompt,
            config: { numberOfImages: 4, outputMimeType: 'image/png', aspectRatio: '1:1' },
        }),
        generateImage(ai, faviconPrompt, { numberOfImages: 1, outputMimeType: 'image/png', aspectRatio: '1:1' }),
        generateImage(ai, fgPrompt, { numberOfImages: 1, outputMimeType: 'image/png', aspectRatio: '1:1' }),
        generateImage(ai, bgPrompt, { numberOfImages: 1, outputMimeType: 'image/png', aspectRatio: '1:1' }),
        generateImage(ai, splashPrompt, { numberOfImages: 1, outputMimeType: 'image/png', aspectRatio: '9:16' }),
    ]);

    if (!standardResponse.generatedImages || standardResponse.generatedImages.length === 0) {
        throw new Error("No standard icons were generated by the API.");
    }

    const standardIcons = standardResponse.generatedImages.map((img) => {
        if (!img.image?.imageBytes) {
            throw new Error("API response missing image data for standard icons.");
        }
        return {
            src: `data:image/png;base64,${img.image.imageBytes}`,
            prompt: prompt,
        };
    });

    const result = {
        favicon: { src: `data:image/png;base64,${faviconImage}`, prompt },
        standard: standardIcons,
        adaptive: {
            foreground: { src: `data:image/png;base64,${fgImage}`, prompt, role: 'foreground' },
            background: { src: `data:image/png;base64,${bgImage}`, prompt, role: 'background' },
        },
        splash: { src: `data:image/png;base64,${splashImage}`, prompt },
    };

    return res.status(200).json(result);

  } catch (error) {
    console.error("Error generating icons:", error);
    const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred while generating icons.';
    return res.status(500).json({ error: `Failed to generate icons: ${errorMessage}` });
  }
}

